name: my cicd pipeline for github action practice

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - name: Run a one-line script
        run: echo this is my first pipeline
