name: my second pipeline
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: action/checkout@v4
        - name: run a single line code
        run: echo this is my second pipeline to execute
